-- Visiagro: tabelas e colunas usadas pelo mapa, lavouras, alertas e relatorios.
-- Execute no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pestes (
  id uuid primary key default gen_random_uuid(),
  nome_cientifico text,
  nome_comum text not null,
  descricao_simples text,
  nivel_risco text,
  periodo_mais_comum text,
  acoes_recomendadas text,
  danos_causados text,
  created_at timestamptz not null default now()
);

create table if not exists public.agrotoxicos (
  id uuid primary key default gen_random_uuid(),
  nome_comercial text,
  ingrediente_ativo text,
  classe text,
  alvo text,
  fabricante text,
  observacoes text,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  peste_id uuid references public.pestes(id) on delete set null,
  filename text,
  label text,
  confianca double precision,
  imagem_url text,
  latitude double precision,
  longitude double precision,
  ativa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.lavouras (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  nome text not null,
  cultura text,
  localizacao text,
  area_hectares double precision,
  raio_alerta_km double precision not null default 5,
  receber_email boolean not null default true,
  latitude double precision,
  longitude double precision,
  boundary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.alertas_publicos (
  id uuid primary key default gen_random_uuid(),
  target_user_id uuid not null references auth.users(id) on delete cascade,
  target_farm_id uuid references public.lavouras(id) on delete cascade,
  source_user_id uuid references auth.users(id) on delete set null,
  prediction_id bigint references public.predictions(id) on delete set null,
  label text,
  confianca double precision,
  latitude double precision,
  longitude double precision,
  nivel_risco text,
  recomendacao text,
  distance_km double precision,
  area_radius_km double precision,
  notified_email_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.technical_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  prediction_id bigint not null references public.predictions(id) on delete cascade,
  produto_recomendado text,
  ingrediente_ativo text,
  dose double precision,
  unidade_dose text,
  volume_calda text,
  modo_aplicacao text,
  prescricao text,
  observacoes text,
  responsavel_tecnico text,
  crea text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prediction_id)
);

alter table public.profiles enable row level security;
alter table public.predictions enable row level security;
alter table public.lavouras enable row level security;
alter table public.alertas_publicos enable row level security;
alter table public.technical_reports enable row level security;
alter table public.pestes enable row level security;
alter table public.agrotoxicos enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "predictions_select_own" on public.predictions;
create policy "predictions_select_own" on public.predictions
  for select using (auth.uid() = user_id);

drop policy if exists "predictions_insert_own" on public.predictions;
create policy "predictions_insert_own" on public.predictions
  for insert with check (auth.uid() = user_id);

drop policy if exists "predictions_update_own" on public.predictions;
create policy "predictions_update_own" on public.predictions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "lavouras_owner_all" on public.lavouras;
create policy "lavouras_owner_all" on public.lavouras
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "alertas_select_target" on public.alertas_publicos;
create policy "alertas_select_target" on public.alertas_publicos
  for select using (auth.uid() = target_user_id);

drop policy if exists "technical_reports_owner_all" on public.technical_reports;
create policy "technical_reports_owner_all" on public.technical_reports
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "pestes_read_authenticated" on public.pestes;
create policy "pestes_read_authenticated" on public.pestes
  for select using (auth.role() = 'authenticated');

drop policy if exists "agrotoxicos_read_authenticated" on public.agrotoxicos;
create policy "agrotoxicos_read_authenticated" on public.agrotoxicos
  for select using (auth.role() = 'authenticated');

create index if not exists predictions_user_created_idx on public.predictions (user_id, created_at desc);
create index if not exists lavouras_user_created_idx on public.lavouras (user_id, created_at desc);
create index if not exists alertas_target_created_idx on public.alertas_publicos (target_user_id, created_at desc);
create index if not exists alertas_farm_prediction_idx on public.alertas_publicos (target_farm_id, prediction_id);
